### ISSUE TITLE
puppet-dotfiles

### ISSUE THREAD

**Issue by jamieconnolly** [boxen/our-boxen#699]
Now that Boxen recommends using per-user hiera configuration, I thought it'd be a good time to make a generic dotfiles module that helps people in cleanly configuring their dotfile setup from within their configuration.

You can find the module [here](https://github.com/jamieconnolly/puppet-dotfiles).

As there's lots of variations on how people structure their dotfile repository, this module is pretty flexible when it comes to creating the symlinks. It handles prefixes and suffixes on both an individual file level, and as a default so complex configurations aren't needed.

Here's how simple it is to set up through Hiera:
``` yaml
dotfiles::dir:      "${boxen::config::srcdir}/dotfiles"
dotfiles::source:   "${::github_login}/dotfiles"

# Configure some defaults for your dotfile repository
dotfiles::prefix:   "."
dotfiles::suffix:   ".symlink"

# Use an array to create symlinks using the default variables
dotfiles::symlinks:
  - editorconfig
  - zshrc

# Use a hash to be more explicit with individual symlinks (will use defaults too)
dotfiles::symlinks:
  zshrc:
    prefix: zsh/
    suffix: .symlink
```

I know it's a bit different from normal boxen-based modules, but I think it's something that reduces a lot of complexity, and it sits nicely alongside all the new functionality of `puppet-boxen/personal.pp`. In my opinion, it would benefit being added to the boxen org
