### ISSUE TITLE
boxen-git-credential error when using different Homebrew root

### ISSUE THREAD

**Issue by salimane** [boxen/our-boxen#727]
```shell
Salimanes-MacBook-Pro:our-boxen salimane$ git push origin master
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:37:in `exec': No such file or directory - /opt/boxen/homebrew/bin/git-credential-osxkeychain (Errno::ENOENT)
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:37:in `block in popen4'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:85:in `call'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:85:in `block in do_popen'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:62:in `fork'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:62:in `do_popen'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:34:in `popen4'
	from /opt/boxen/bin/boxen-git-credential:45:in `<main>'
Counting objects: 909, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (546/546), done.
Writing objects: 100% (793/793), 43.67 MiB | 224.00 KiB/s, done.
Total 793 (delta 286), reused 604 (delta 234)
To https://github.com/salimane/our-boxen
   7e677e1..7652f6b  master -> master
Salimanes-MacBook-Pro:our-boxen salimane$ 

```

**Comment by seanknox** [comment]
`/opt/boxen/homebrew/bin/git-credential-osxkeychain` is not present. Any idea how it would have been removed?

**Comment by salimane** [comment]
here is the content of my  ``our-boxen/facts.d/common.yaml``. I'm using ``/usr/local`` as my homebrew path
```yaml
---
# Any yaml or json files in this directory may be used to set
# facts. This is useful, primarily, for things like homebrew_root,
# which must be a fact rather than configured with hiera because
# of how Puppet's custom resource providers work.

homebrew_root: /usr/local
brewcask_root: /opt/homebrew-cask

```
